=== B-O-A-J-P/Proyecto-Kings-League-prueba/LenguajeDeMarcas/Calendario_kings_league.dtd
<!ELEMENT temporada (SPLIT+)>
<!ELEMENT SPLIT (SPLITS_XML+)>
<!ELEMENT SPLITS_XML  (FECHA_INICIO,FECHA_FIN,JORNADA+)>
<!ELEMENT FECHA_INICIO (#PCDATA)>
<!ELEMENT FECHA_FIN (#PCDATA)>
<!ELEMENT JORNADA (JORNADAS_XML*)>
<!ELEMENT JORNADAS_XML  (FECHA,PARTIDO+)>
<!ELEMENT FECHA (#PCDATA)>
<!ELEMENT PARTIDO (PARTIDOS_XML+)>
 <!ELEMENT PARTIDOS_XML  (HORA,EQUIPO_LOCAL, EQUIPO_VISITANTE)>
<!ELEMENT HORA (#PCDATA)>
<!ELEMENT EQUIPO_LOCAL (NOMBRE,LOGO) >
<!ELEMENT EQUIPO_VISITANTE (NOMBRE,LOGO) >
<!ELEMENT LOGO (#PCDATA)>
<!ELEMENT NOMBRE (#PCDATA)>


<!ATTLIST temporada ID  NMTOKEN #REQUIRED>
<!ATTLIST SPLITS_XML ID  NMTOKEN #REQUIRED>
<!ATTLIST JORNADAS_XML ID NMTOKEN #REQUIRED>
<!ATTLIST PARTIDOS_XML ID  NMTOKEN #REQUIRED>
<!ATTLIST EQUIPO_LOCAL ID  NMTOKEN #REQUIRED>
<!ATTLIST EQUIPO_VISITANTE ID  NMTOKEN #REQUIRED>
<!ATTLIST LOGO empty  CDATA #REQUIRED>

=== B-O-A-J-P/Proyecto-Kings-League-prueba/LenguajeDeMarcas/CALENDARIO_JORNADAS.xml
<!DOCTYPE temporada SYSTEM "Calendario_kings_league.dtd">

<temporada ID="0" xmlns:xs = "http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation = "Calendario_kings_League.xsd">

  <SPLIT>
   <SPLITS_XML ID="0">
    <FECHA_INICIO>01/07/24</FECHA_INICIO>
    <FECHA_FIN>31/07/24</FECHA_FIN>
    <JORNADA>
     <JORNADAS_XML ID="0">
      <FECHA>01/07/24</FECHA>
      <PARTIDO>
       <PARTIDOS_XML ID="0">
        <HORA>2024-07-01T19:00:00</HORA>
        <EQUIPO_LOCAL ID="9">
         <NOMBRE>Equipo 10</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="0">
         <NOMBRE>Equipo 1</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="1">
        <HORA>2024-07-01T20:00:00</HORA>
        <EQUIPO_LOCAL ID="8">
         <NOMBRE>Equipo 9</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="10">
         <NOMBRE>Equipo 11</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="2">
        <HORA>2024-07-01T21:00:00</HORA>
        <EQUIPO_LOCAL ID="3">
         <NOMBRE>Equipo 4</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="2">
         <NOMBRE>Equipo 3</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="3">
        <HORA>2024-07-01T22:00:00</HORA>
        <EQUIPO_LOCAL ID="7">
         <NOMBRE>Equipo 8</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="5">
         <NOMBRE>Equipo 6</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="4">
        <HORA>2024-07-01T23:00:00</HORA>
        <EQUIPO_LOCAL ID="6">
         <NOMBRE>Equipo 7</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="1">
         <NOMBRE>Equipo 2</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="5">
        <HORA>2024-07-02T00:00:00</HORA>
        <EQUIPO_LOCAL ID="4">
         <NOMBRE>Equipo 5</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="11">
         <NOMBRE>Equipo 12</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
      </PARTIDO>
     </JORNADAS_XML>
     <JORNADAS_XML ID="1">
      <FECHA>08/07/24</FECHA>
      <PARTIDO>
       <PARTIDOS_XML ID="6">
        <HORA>2024-07-08T19:00:00</HORA>
        <EQUIPO_LOCAL ID="2">
         <NOMBRE>Equipo 3</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="6">
         <NOMBRE>Equipo 7</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="7">
        <HORA>2024-07-08T20:00:00</HORA>
        <EQUIPO_LOCAL ID="11">
         <NOMBRE>Equipo 12</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="5">
         <NOMBRE>Equipo 6</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="8">
        <HORA>2024-07-08T21:00:00</HORA>
        <EQUIPO_LOCAL ID="0">
         <NOMBRE>Equipo 1</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="3">
         <NOMBRE>Equipo 4</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="9">
        <HORA>2024-07-08T22:00:00</HORA>
        <EQUIPO_LOCAL ID="9">
         <NOMBRE>Equipo 10</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="4">
         <NOMBRE>Equipo 5</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="10">
        <HORA>2024-07-08T23:00:00</HORA>
        <EQUIPO_LOCAL ID="10">
         <NOMBRE>Equipo 11</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="8">
         <NOMBRE>Equipo 9</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="11">
        <HORA>2024-07-09T00:00:00</HORA>
        <EQUIPO_LOCAL ID="7">
         <NOMBRE>Equipo 8</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="1">
         <NOMBRE>Equipo 2</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
      </PARTIDO>
     </JORNADAS_XML>
     <JORNADAS_XML ID="2">
      <FECHA>15/07/24</FECHA>
      <PARTIDO>
       <PARTIDOS_XML ID="12">
        <HORA>2024-07-15T19:00:00</HORA>
        <EQUIPO_LOCAL ID="1">
         <NOMBRE>Equipo 2</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="4">
         <NOMBRE>Equipo 5</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="13">
        <HORA>2024-07-15T20:00:00</HORA>
        <EQUIPO_LOCAL ID="6">
         <NOMBRE>Equipo 7</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="0">
         <NOMBRE>Equipo 1</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="14">
        <HORA>2024-07-15T21:00:00</HORA>
        <EQUIPO_LOCAL ID="2">
         <NOMBRE>Equipo 3</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="3">
         <NOMBRE>Equipo 4</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="15">
        <HORA>2024-07-15T22:00:00</HORA>
        <EQUIPO_LOCAL ID="10">
         <NOMBRE>Equipo 11</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="11">
         <NOMBRE>Equipo 12</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="16">
        <HORA>2024-07-15T23:00:00</HORA>
        <EQUIPO_LOCAL ID="9">
         <NOMBRE>Equipo 10</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="7">
         <NOMBRE>Equipo 8</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="17">
        <HORA>2024-07-16T00:00:00</HORA>
        <EQUIPO_LOCAL ID="5">
         <NOMBRE>Equipo 6</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="8">
         <NOMBRE>Equipo 9</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
      </PARTIDO>
     </JORNADAS_XML>
     <JORNADAS_XML ID="3">
      <FECHA>22/07/24</FECHA>
      <PARTIDO>
       <PARTIDOS_XML ID="18">
        <HORA>2024-07-22T19:00:00</HORA>
        <EQUIPO_LOCAL ID="0">
         <NOMBRE>Equipo 1</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="6">
         <NOMBRE>Equipo 7</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="19">
        <HORA>2024-07-22T20:00:00</HORA>
        <EQUIPO_LOCAL ID="7">
         <NOMBRE>Equipo 8</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="2">
         <NOMBRE>Equipo 3</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="20">
        <HORA>2024-07-22T21:00:00</HORA>
        <EQUIPO_LOCAL ID="1">
         <NOMBRE>Equipo 2</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="9">
         <NOMBRE>Equipo 10</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="21">
        <HORA>2024-07-22T22:00:00</HORA>
        <EQUIPO_LOCAL ID="8">
         <NOMBRE>Equipo 9</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="11">
         <NOMBRE>Equipo 12</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="22">
        <HORA>2024-07-22T23:00:00</HORA>
        <EQUIPO_LOCAL ID="4">
         <NOMBRE>Equipo 5</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="10">
         <NOMBRE>Equipo 11</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="23">
        <HORA>2024-07-23T00:00:00</HORA>
        <EQUIPO_LOCAL ID="3">
         <NOMBRE>Equipo 4</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="5">
         <NOMBRE>Equipo 6</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
      </PARTIDO>
     </JORNADAS_XML>
     <JORNADAS_XML ID="4">
      <FECHA>29/07/24</FECHA>
      <PARTIDO>
       <PARTIDOS_XML ID="24">
        <HORA>2024-07-29T19:00:00</HORA>
        <EQUIPO_LOCAL ID="10">
         <NOMBRE>Equipo 11</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="11">
         <NOMBRE>Equipo 12</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="25">
        <HORA>2024-07-29T20:00:00</HORA>
        <EQUIPO_LOCAL ID="7">
         <NOMBRE>Equipo 8</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="1">
         <NOMBRE>Equipo 2</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="26">
        <HORA>2024-07-29T21:00:00</HORA>
        <EQUIPO_LOCAL ID="2">
         <NOMBRE>Equipo 3</NOMBRE>
         <LOGO empty="blob"/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="4">
         <NOMBRE>Equipo 5</NOMBRE>
         <LOGO empty="blob"/>
