=== B-O-A-J-P/Proyecto-Kings-League-prueba/LenguajeDeMarcas/clasificacion.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="temporada" type="TemporadaType"/>

  <xs:complexType name="TemporadaType">
    <xs:sequence>
      <xs:element name="SPLIT" type="TipoSplit" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
        <xs:attribute name="ID" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="TipoSplit">
    <xs:sequence>
      <xs:element name="SPLIT_TIPO" type="SplitTipoType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>

  </xs:complexType>

  <xs:complexType name="SplitTipoType">
    <xs:sequence>
      <xs:element name="CLASIFICACION" type="TipoClasificacion"/>
    </xs:sequence>
        <xs:attribute name="ID" type="xs:string" use="required"/>

  </xs:complexType>

  <xs:complexType name="TipoClasificacion">
    <xs:sequence>
      <xs:element name="EQUIPO" type="TipoEquipo" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="fecha_fin" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="TipoEquipo">
    <xs:sequence>
      <xs:element name="EQUIPO_TIPO" type="EquipoTipoType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="EquipoTipoType">
    <xs:sequence>
      <xs:element name="NOMBRE" type="xs:string"/>
      <xs:element name="LOGO" type="LogoType"/>
      <xs:element name="PUNTOS" type="xs:integer"/>
      <xs:element name="GOLES" type="StringVacio" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="ID" type="xs:string" use="required"/>
  </xs:complexType>
  
  <xs:simpleType name="StringVacio">
    <xs:union memberTypes="xs:string">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value=""/>
        </xs:restriction>
      </xs:simpleType>
    </xs:union>
  </xs:simpleType>

  <xs:complexType name="LogoType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="empty" type="xs:string"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

</xs:schema>

=== B-O-A-J-P/Proyecto-Kings-League-prueba/LenguajeDeMarcas/clasificacion.xml
<?xml version="1.0"?>
<!DOCTYPE temporada SYSTEM "kings_league_clasificacion.dtd">

 <temporada ID="0" xmlns:xs = "http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation = "clasificacion.xsd">
  <SPLIT>
   <SPLIT_TIPO ID="0">
    <CLASIFICACION fecha_fin="31/07/24">
     <EQUIPO>
      <EQUIPO_TIPO ID="0">
       <NOMBRE>Equipo 1</NOMBRE>
       <LOGO empty="blob"/>
       <PUNTOS>0</PUNTOS>
       <GOLES/>
      </EQUIPO_TIPO>
      <EQUIPO_TIPO ID="1">
       <NOMBRE>Equipo 2</NOMBRE>
       <LOGO empty="blob"/>
       <PUNTOS>0</PUNTOS>
       <GOLES/>
      </EQUIPO_TIPO>
      <EQUIPO_TIPO ID="2">
       <NOMBRE>Equipo 3</NOMBRE>
       <LOGO empty="blob"/>
       <PUNTOS>1</PUNTOS>
       <GOLES>1</GOLES>
      </EQUIPO_TIPO>
      <EQUIPO_TIPO ID="3">
       <NOMBRE>Equipo 4</NOMBRE>
       <LOGO empty="blob"/>
       <PUNTOS>1</PUNTOS>
       <GOLES>2</GOLES>
      </EQUIPO_TIPO>
      <EQUIPO_TIPO ID="4">
       <NOMBRE>Equipo 5</NOMBRE>
       <LOGO empty="blob"/>
       <PUNTOS>1</PUNTOS>
       <GOLES>0</GOLES>
      </EQUIPO_TIPO>
      <EQUIPO_TIPO ID="5">
       <NOMBRE>Equipo 6</NOMBRE>
       <LOGO empty="blob"/>
       <PUNTOS>0</PUNTOS>
       <GOLES/>
      </EQUIPO_TIPO>
      <EQUIPO_TIPO ID="6">
       <NOMBRE>Equipo 7</NOMBRE>
       <LOGO empty="blob"/>
       <PUNTOS>1</PUNTOS>
       <GOLES>4</GOLES>
      </EQUIPO_TIPO>
      <EQUIPO_TIPO ID="7">
       <NOMBRE>Equipo 8</NOMBRE>
       <LOGO empty="blob"/>
       <PUNTOS>1</PUNTOS>
       <GOLES>3</GOLES>
      </EQUIPO_TIPO>
      <EQUIPO_TIPO ID="8">
       <NOMBRE>Equipo 9</NOMBRE>
       <LOGO empty="blob"/>
       <PUNTOS>1</PUNTOS>
       <GOLES>1</GOLES>
      </EQUIPO_TIPO>
      <EQUIPO_TIPO ID="9">
       <NOMBRE>Equipo 10</NOMBRE>
       <LOGO empty="blob"/>
       <PUNTOS>1</PUNTOS>
       <GOLES>2</GOLES>
      </EQUIPO_TIPO>
      <EQUIPO_TIPO ID="10">
       <NOMBRE>Equipo 11</NOMBRE>
       <LOGO empty="blob"/>
       <PUNTOS>0</PUNTOS>
       <GOLES/>
      </EQUIPO_TIPO>
      <EQUIPO_TIPO ID="11">
       <NOMBRE>Equipo 12</NOMBRE>
       <LOGO empty="blob"/>
       <PUNTOS>1</PUNTOS>
       <GOLES>0</GOLES>
      </EQUIPO_TIPO>
     </EQUIPO>
    </CLASIFICACION>
   </SPLIT_TIPO>
   <SPLIT_TIPO ID="1">
    <CLASIFICACION fecha_fin="31/07/24">
     <EQUIPO/>
    </CLASIFICACION>
   </SPLIT_TIPO>
  </SPLIT>
 </temporada>
