=== B-O-A-J-P/Proyecto-Kings-League-prueba/LenguajeDeMarcas/jornada.dtd
<!ELEMENT temporada (SPLITS+)>
<!ELEMENT SPLITS (SPLITS_XML+)>
<!ELEMENT SPLITS_XML (JORNADAS+)>
<!ELEMENT JORNADAS (JORNADAS_XML+)>
<!ELEMENT JORNADAS_XML (PARTIDOS+)>
<!ELEMENT PARTIDOS (PARTIDOS_XML+)>
<!ELEMENT PARTIDOS_XML ( HORA, EQUIPO_LOCAL, EQUIPO_VISITANTE)>
<!ELEMENT HORA (#PCDATA)>
<!ELEMENT EQUIPO_LOCAL (NOMBRE, LOGO, NUMERO_GOLES, RESULTADO)>
<!ELEMENT EQUIPO_VISITANTE (NOMBRE, LOGO, NUMERO_GOLES, RESULTADO)>
<!ELEMENT NOMBRE (#PCDATA)>
<!ELEMENT LOGO (#PCDATA)>
<!ELEMENT NUMERO_GOLES (#PCDATA)>
<!ELEMENT RESULTADO  (#PCDATA)>

<!ATTLIST temporada ID NMTOKEN #REQUIRED>
<!ATTLIST SPLITS_XML ID NMTOKEN #IMPLIED>
<!ATTLIST JORNADAS_XML ID NMTOKEN #IMPLIED>
<!ATTLIST PARTIDOS_XML ID NMTOKEN #IMPLIED>
<!ATTLIST EQUIPO_LOCAL ID NMTOKEN #REQUIRED>
<!ATTLIST EQUIPO_VISITANTE ID NMTOKEN #REQUIRED>
<!ATTLIST LOGO empty  CDATA #REQUIRED>

=== B-O-A-J-P/Proyecto-Kings-League-prueba/LenguajeDeMarcas/resultado_jornadas.xml
<?xml version="1.0" encoding="Cp1252"?>
<!DOCTYPE temporada SYSTEM "jornada.dtd">
<temporada xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" ID="0" xs:noNamespaceSchemaLocation="jornada.xsd">
  <SPLITS>
   <SPLITS_XML ID="0">
    <JORNADAS>
     <JORNADAS_XML ID="0">
      <PARTIDOS>
       <PARTIDOS_XML ID="0">
        <HORA>2024-07-01T19:00:00</HORA>
        <EQUIPO_LOCAL ID="9">
         <NOMBRE>Equipo 10</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES>2</NUMERO_GOLES>
         <RESULTADO>v</RESULTADO>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="0">
         <NOMBRE>Equipo 1</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES>0</NUMERO_GOLES>
         <RESULTADO>d</RESULTADO>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="1">
        <HORA>2024-07-01T20:00:00</HORA>
        <EQUIPO_LOCAL ID="8">
         <NOMBRE>Equipo 9</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES>1</NUMERO_GOLES>
         <RESULTADO>v</RESULTADO>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="10">
         <NOMBRE>Equipo 11</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES>3</NUMERO_GOLES>
         <RESULTADO>d</RESULTADO>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="2">
        <HORA>2024-07-01T21:00:00</HORA>
        <EQUIPO_LOCAL ID="3">
         <NOMBRE>Equipo 4</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES>2</NUMERO_GOLES>
         <RESULTADO>v</RESULTADO>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="2">
         <NOMBRE>Equipo 3</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES>0</NUMERO_GOLES>
         <RESULTADO>d</RESULTADO>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="3">
        <HORA>2024-07-01T22:00:00</HORA>
        <EQUIPO_LOCAL ID="7">
         <NOMBRE>Equipo 8</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES>3</NUMERO_GOLES>
         <RESULTADO>v</RESULTADO>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="5">
         <NOMBRE>Equipo 6</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES>1</NUMERO_GOLES>
         <RESULTADO>d</RESULTADO>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="4">
        <HORA>2024-07-01T23:00:00</HORA>
        <EQUIPO_LOCAL ID="6">
         <NOMBRE>Equipo 7</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES>4</NUMERO_GOLES>
         <RESULTADO>v</RESULTADO>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="1">
         <NOMBRE>Equipo 2</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES>1</NUMERO_GOLES>
         <RESULTADO>d</RESULTADO>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="5">
        <HORA>2024-07-02T00:00:00</HORA>
        <EQUIPO_LOCAL ID="4">
         <NOMBRE>Equipo 5</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES>0</NUMERO_GOLES>
         <RESULTADO>v</RESULTADO>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="11">
         <NOMBRE>Equipo 12</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES>3</NUMERO_GOLES>
         <RESULTADO>d</RESULTADO>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
      </PARTIDOS>
     </JORNADAS_XML>
     <JORNADAS_XML ID="1">
      <PARTIDOS>
       <PARTIDOS_XML ID="6">
        <HORA>2024-07-08T19:00:00</HORA>
        <EQUIPO_LOCAL ID="2">
         <NOMBRE>Equipo 3</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES>1</NUMERO_GOLES>
         <RESULTADO>v</RESULTADO>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="6">
         <NOMBRE>Equipo 7</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES>1</NUMERO_GOLES>
         <RESULTADO>d</RESULTADO>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="7">
        <HORA>2024-07-08T20:00:00</HORA>
        <EQUIPO_LOCAL ID="11">
         <NOMBRE>Equipo 12</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES>0</NUMERO_GOLES>
         <RESULTADO>v</RESULTADO>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="5">
         <NOMBRE>Equipo 6</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES>1</NUMERO_GOLES>
         <RESULTADO>d</RESULTADO>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="8">
        <HORA>2024-07-08T21:00:00</HORA>
        <EQUIPO_LOCAL ID="0">
         <NOMBRE>Equipo 1</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES/>
         <RESULTADO/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="3">
         <NOMBRE>Equipo 4</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES/>
         <RESULTADO/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="9">
        <HORA>2024-07-08T22:00:00</HORA>
        <EQUIPO_LOCAL ID="9">
         <NOMBRE>Equipo 10</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES/>
         <RESULTADO/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="4">
         <NOMBRE>Equipo 5</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES/>
         <RESULTADO/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="10">
        <HORA>2024-07-08T23:00:00</HORA>
        <EQUIPO_LOCAL ID="10">
         <NOMBRE>Equipo 11</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES/>
         <RESULTADO/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="8">
         <NOMBRE>Equipo 9</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES/>
         <RESULTADO/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="11">
        <HORA>2024-07-09T00:00:00</HORA>
        <EQUIPO_LOCAL ID="7">
         <NOMBRE>Equipo 8</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES/>
         <RESULTADO/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="1">
         <NOMBRE>Equipo 2</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES/>
         <RESULTADO/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
      </PARTIDOS>
     </JORNADAS_XML>
     <JORNADAS_XML ID="2">
      <PARTIDOS>
       <PARTIDOS_XML ID="12">
        <HORA>2024-07-15T19:00:00</HORA>
        <EQUIPO_LOCAL ID="1">
         <NOMBRE>Equipo 2</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES/>
         <RESULTADO/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="4">
         <NOMBRE>Equipo 5</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES/>
         <RESULTADO/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="13">
        <HORA>2024-07-15T20:00:00</HORA>
        <EQUIPO_LOCAL ID="6">
         <NOMBRE>Equipo 7</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES/>
         <RESULTADO/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="0">
         <NOMBRE>Equipo 1</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES/>
         <RESULTADO/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="14">
        <HORA>2024-07-15T21:00:00</HORA>
        <EQUIPO_LOCAL ID="2">
         <NOMBRE>Equipo 3</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES/>
         <RESULTADO/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="3">
         <NOMBRE>Equipo 4</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES/>
         <RESULTADO/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="15">
        <HORA>2024-07-15T22:00:00</HORA>
        <EQUIPO_LOCAL ID="10">
         <NOMBRE>Equipo 11</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES/>
         <RESULTADO/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="11">
         <NOMBRE>Equipo 12</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES/>
         <RESULTADO/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="16">
        <HORA>2024-07-15T23:00:00</HORA>
        <EQUIPO_LOCAL ID="9">
         <NOMBRE>Equipo 10</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES/>
         <RESULTADO/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="7">
         <NOMBRE>Equipo 8</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES/>
         <RESULTADO/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="17">
        <HORA>2024-07-16T00:00:00</HORA>
        <EQUIPO_LOCAL ID="5">
         <NOMBRE>Equipo 6</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES/>
         <RESULTADO/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="8">
         <NOMBRE>Equipo 9</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES/>
         <RESULTADO/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
      </PARTIDOS>
     </JORNADAS_XML>
     <JORNADAS_XML ID="3">
      <PARTIDOS>
       <PARTIDOS_XML ID="18">
        <HORA>2024-07-22T19:00:00</HORA>
        <EQUIPO_LOCAL ID="0">
         <NOMBRE>Equipo 1</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES/>
         <RESULTADO/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="6">
         <NOMBRE>Equipo 7</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES/>
         <RESULTADO/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="19">
        <HORA>2024-07-22T20:00:00</HORA>
        <EQUIPO_LOCAL ID="7">
         <NOMBRE>Equipo 8</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES/>
         <RESULTADO/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="2">
         <NOMBRE>Equipo 3</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES/>
         <RESULTADO/>
        </EQUIPO_VISITANTE>
       </PARTIDOS_XML>
       <PARTIDOS_XML ID="20">
        <HORA>2024-07-22T21:00:00</HORA>
        <EQUIPO_LOCAL ID="1">
         <NOMBRE>Equipo 2</NOMBRE>
         <LOGO empty="blob"/>
         <NUMERO_GOLES/>
         <RESULTADO/>
        </EQUIPO_LOCAL>
        <EQUIPO_VISITANTE ID="9">
         <NOMBRE>Equipo 10</NOMBRE>
         <LOGO empty="blob"/>
