=== B-O-A-J-P/Proyecto-Kings-League-prueba/LenguajeDeMarcas/play_offs.dtd
<!ELEMENT temporada (SPLIT)>
<!ELEMENT SPLIT (SPLITS_XML+)>
<!ELEMENT SPLITS_XML (PARTIDO+)>
<!ELEMENT PARTIDO (PARTIDOS_XML+)>
<!ELEMENT PARTIDOS_XML (HORA,UBICACION,FASE,EQUIPO_LOCAL,EQUIPO_VISITANTE)>
<!ELEMENT HORA (#PCDATA)>
<!ELEMENT UBICACION (#PCDATA)>
<!ELEMENT FASE (#PCDATA)>
<!ELEMENT EQUIPO_LOCAL (NOMBRE,LOGO,NUMERO_GOLES,RESULTADO)>
<!ELEMENT EQUIPO_VISITANTE (NOMBRE,LOGO,NUMERO_GOLES,RESULTADO)>
<!ELEMENT NOMBRE (#PCDATA)>
<!ELEMENT LOGO EMPTY>
<!ELEMENT NUMERO_GOLES (#PCDATA)>
<!ELEMENT RESULTADO (#PCDATA)>

<!ATTLIST temporada ID  NMTOKEN #REQUIRED>
<!ATTLIST SPLITS_XML ID NMTOKEN #REQUIRED>
<!ATTLIST PARTIDOS_XML ID NMTOKEN #REQUIRED>
<!ATTLIST EQUIPO_LOCAL ID  NMTOKEN #REQUIRED>
<!ATTLIST EQUIPO_VISITANTE ID  NMTOKEN #REQUIRED>
<!ATTLIST LOGO empty  CDATA #REQUIRED>

=== B-O-A-J-P/Proyecto-Kings-League-prueba/LenguajeDeMarcas/play_offs.xml
<!DOCTYPE temporada SYSTEM "play_offs.dtd">
 <temporada ID="0" xmlns:xs = "http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation = "play_offs.xsd">
  <SPLIT>
   <SPLITS_XML ID="0">
    <PARTIDO>
     <PARTIDOS_XML ID="146">
      <HORA>2024-09-23T12:00:00</HORA>
      <UBICACION>EN EL FIN DEL MUNDO</UBICACION>
      <FASE>r</FASE>
      <EQUIPO_LOCAL ID="0">
       <NOMBRE>Equipo 1</NOMBRE>
       <LOGO empty="blob"/>
       <NUMERO_GOLES/>
       <RESULTADO/>
      </EQUIPO_LOCAL>
      <EQUIPO_VISITANTE ID="7">
       <NOMBRE>Equipo 8</NOMBRE>
       <LOGO empty="blob"/>
       <NUMERO_GOLES/>
       <RESULTADO/>
      </EQUIPO_VISITANTE>
     </PARTIDOS_XML>
     <PARTIDOS_XML ID="147">
      <HORA>2024-09-23T13:00:00</HORA>
      <UBICACION>EN EL FIN DEL MUNDO</UBICACION>
      <FASE>r</FASE>
      <EQUIPO_LOCAL ID="1">
       <NOMBRE>Equipo 2</NOMBRE>
       <LOGO empty="blob"/>
       <NUMERO_GOLES/>
       <RESULTADO/>
      </EQUIPO_LOCAL>
      <EQUIPO_VISITANTE ID="6">
       <NOMBRE>Equipo 7</NOMBRE>
       <LOGO empty="blob"/>
       <NUMERO_GOLES/>
       <RESULTADO/>
      </EQUIPO_VISITANTE>
     </PARTIDOS_XML>
     <PARTIDOS_XML ID="148">
      <HORA>2024-09-23T14:00:00</HORA>
      <UBICACION>EN EL FIN DEL MUNDO</UBICACION>
      <FASE>r</FASE>
      <EQUIPO_LOCAL ID="2">
       <NOMBRE>Equipo 3</NOMBRE>
       <LOGO empty="blob"/>
       <NUMERO_GOLES/>
       <RESULTADO/>
      </EQUIPO_LOCAL>
      <EQUIPO_VISITANTE ID="5">
       <NOMBRE>Equipo 6</NOMBRE>
       <LOGO empty="blob"/>
       <NUMERO_GOLES/>
       <RESULTADO/>
      </EQUIPO_VISITANTE>
     </PARTIDOS_XML>
     <PARTIDOS_XML ID="149">
      <HORA>2024-09-23T15:00:00</HORA>
      <UBICACION>EN EL FIN DEL MUNDO</UBICACION>
      <FASE>r</FASE>
      <EQUIPO_LOCAL ID="3">
       <NOMBRE>Equipo 4</NOMBRE>
       <LOGO empty="blob"/>
       <NUMERO_GOLES/>
       <RESULTADO/>
      </EQUIPO_LOCAL>
      <EQUIPO_VISITANTE ID="4">
       <NOMBRE>Equipo 5</NOMBRE>
       <LOGO empty="blob"/>
       <NUMERO_GOLES/>
       <RESULTADO/>
      </EQUIPO_VISITANTE>
     </PARTIDOS_XML>
    </PARTIDO>
   </SPLITS_XML>
   <SPLITS_XML ID="1">
    <PARTIDO>
     <PARTIDOS_XML ID="146">
      <HORA>2024-09-23T12:00:00</HORA>
      <UBICACION>EN EL FIN DEL MUNDO</UBICACION>
      <FASE>r</FASE>
      <EQUIPO_LOCAL ID="0">
       <NOMBRE>Equipo 1</NOMBRE>
       <LOGO empty="blob"/>
       <NUMERO_GOLES/>
       <RESULTADO/>
      </EQUIPO_LOCAL>
      <EQUIPO_VISITANTE ID="7">
       <NOMBRE>Equipo 8</NOMBRE>
       <LOGO empty="blob"/>
       <NUMERO_GOLES/>
       <RESULTADO/>
      </EQUIPO_VISITANTE>
     </PARTIDOS_XML>
     <PARTIDOS_XML ID="147">
      <HORA>2024-09-23T13:00:00</HORA>
      <UBICACION>EN EL FIN DEL MUNDO</UBICACION>
      <FASE>r</FASE>
      <EQUIPO_LOCAL ID="1">
       <NOMBRE>Equipo 2</NOMBRE>
       <LOGO empty="blob"/>
       <NUMERO_GOLES/>
       <RESULTADO/>
      </EQUIPO_LOCAL>
      <EQUIPO_VISITANTE ID="6">
       <NOMBRE>Equipo 7</NOMBRE>
       <LOGO empty="blob"/>
       <NUMERO_GOLES/>
       <RESULTADO/>
      </EQUIPO_VISITANTE>
     </PARTIDOS_XML>
     <PARTIDOS_XML ID="148">
      <HORA>2024-09-23T14:00:00</HORA>
      <UBICACION>EN EL FIN DEL MUNDO</UBICACION>
      <FASE>r</FASE>
      <EQUIPO_LOCAL ID="2">
       <NOMBRE>Equipo 3</NOMBRE>
       <LOGO empty="blob"/>
       <NUMERO_GOLES/>
       <RESULTADO/>
      </EQUIPO_LOCAL>
      <EQUIPO_VISITANTE ID="5">
       <NOMBRE>Equipo 6</NOMBRE>
       <LOGO empty="blob"/>
       <NUMERO_GOLES/>
       <RESULTADO/>
      </EQUIPO_VISITANTE>
     </PARTIDOS_XML>
     <PARTIDOS_XML ID="149">
      <HORA>2024-09-23T15:00:00</HORA>
      <UBICACION>EN EL FIN DEL MUNDO</UBICACION>
      <FASE>r</FASE>
      <EQUIPO_LOCAL ID="3">
       <NOMBRE>Equipo 4</NOMBRE>
       <LOGO empty="blob"/>
       <NUMERO_GOLES/>
       <RESULTADO/>
      </EQUIPO_LOCAL>
      <EQUIPO_VISITANTE ID="4">
       <NOMBRE>Equipo 5</NOMBRE>
       <LOGO empty="blob"/>
       <NUMERO_GOLES/>
       <RESULTADO/>
      </EQUIPO_VISITANTE>
     </PARTIDOS_XML>
    </PARTIDO>
   </SPLITS_XML>
  </SPLIT>
 </temporada>
